[2024-09-07T12:54:14.037+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T12:54:14.106+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-25T00:00:00+00:00 [queued]>
[2024-09-07T12:54:14.122+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-25T00:00:00+00:00 [queued]>
[2024-09-07T12:54:14.123+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-07T12:54:14.145+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_to_warehouse> on 2024-01-25 00:00:00+00:00
[2024-09-07T12:54:14.158+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1149) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-07T12:54:14.159+0000] {standard_task_runner.py:63} INFO - Started process 1152 to run task
[2024-09-07T12:54:14.157+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl', 'load_data_to_warehouse', 'scheduled__2024-01-25T00:00:00+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/reddit.py', '--cfg-path', '/tmp/tmpr6t06_eo']
[2024-09-07T12:54:14.160+0000] {standard_task_runner.py:91} INFO - Job 288: Subtask load_data_to_warehouse
[2024-09-07T12:54:14.252+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-25T00:00:00+00:00 [running]> on host 42d604ea5ce6
[2024-09-07T12:54:14.429+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reddithackathon' AIRFLOW_CTX_DAG_ID='reddit_etl' AIRFLOW_CTX_TASK_ID='load_data_to_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-25T00:00:00+00:00'
[2024-09-07T12:54:14.430+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T12:54:14.476+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.477+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.477+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.477+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.478+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.478+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.479+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.479+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.479+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.480+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.480+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.480+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.481+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.481+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.481+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.482+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.482+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.482+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.483+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.483+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.483+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.484+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.484+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.485+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.485+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.485+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.486+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.486+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.486+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.487+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.487+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.487+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.488+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.488+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.488+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.489+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.489+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.489+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.490+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.490+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.491+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.491+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.491+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.492+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.492+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.492+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.493+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.493+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.493+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.494+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.494+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.494+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.495+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.495+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.495+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.496+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.496+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.496+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.497+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.497+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.497+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.498+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.498+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.498+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.499+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.499+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.499+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.500+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.500+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.500+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.501+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.501+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.502+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.502+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.502+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.503+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.503+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.503+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.504+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.504+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.505+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.505+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.505+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.506+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.506+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.507+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.507+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.507+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.508+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.508+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.508+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.509+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.509+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.510+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.510+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.510+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.511+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.511+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.511+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.512+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.512+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.513+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.513+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.513+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.514+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.514+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.515+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.515+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.515+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.516+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.516+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.516+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.517+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.517+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.517+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.518+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.518+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.518+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.519+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.519+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.519+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.520+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.520+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.521+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.521+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.521+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.522+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.522+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.522+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.523+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.523+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.524+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.524+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.524+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.525+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.525+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.525+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.526+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.526+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.526+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.527+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.527+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.527+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.528+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.528+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.528+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.529+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.529+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.529+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.530+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.530+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.531+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.531+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.531+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.532+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.532+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.533+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.533+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.533+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.534+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.534+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.534+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.535+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.535+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.535+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.536+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.536+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.536+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.537+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.537+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.538+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.538+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.538+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.539+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.539+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.540+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.540+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.540+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.541+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.541+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.541+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.542+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.542+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.543+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.543+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.543+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.544+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.544+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.545+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.545+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.545+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.546+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.546+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.547+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.547+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.547+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.548+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.548+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.548+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.549+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.549+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.550+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.550+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.550+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.551+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.551+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.552+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.552+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.552+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.553+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.553+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.554+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.554+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.554+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.555+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.555+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.556+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.556+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.556+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.557+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.557+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.557+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.558+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.558+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.558+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.559+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.559+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.559+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.560+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.560+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.560+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.561+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.561+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.561+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.562+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.562+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.562+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.563+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.563+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.563+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.564+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.564+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.564+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.565+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.565+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.565+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.566+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.566+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.566+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.567+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.567+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.567+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.567+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.568+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.568+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.568+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.569+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.569+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.569+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.570+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.570+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.571+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.571+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.571+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.571+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.572+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.572+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.573+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.573+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.573+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.574+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.574+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.574+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.575+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.575+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.576+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.576+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.577+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.577+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.577+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.578+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.578+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.579+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.579+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.579+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.580+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.580+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.580+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.581+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.581+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.582+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.582+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.582+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.583+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.583+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.583+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.584+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.584+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.584+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.585+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:14.585+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-07T12:54:14.585+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T12:54:14.603+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=reddit_etl, task_id=load_data_to_warehouse, execution_date=20240125T000000, start_date=20240907T125414, end_date=20240907T125414
[2024-09-07T12:54:14.653+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-07T12:54:14.688+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T12:54:14.689+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-07T13:51:20.524+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T13:51:20.670+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-25T00:00:00+00:00 [queued]>
[2024-09-07T13:51:20.703+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-25T00:00:00+00:00 [queued]>
[2024-09-07T13:51:20.704+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-07T13:51:21.024+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_to_warehouse> on 2024-01-25 00:00:00+00:00
[2024-09-07T13:51:21.079+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=739) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-07T13:51:21.082+0000] {standard_task_runner.py:63} INFO - Started process 744 to run task
[2024-09-07T13:51:21.078+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl', 'load_data_to_warehouse', 'scheduled__2024-01-25T00:00:00+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/reddit.py', '--cfg-path', '/tmp/tmpvabomi4t']
[2024-09-07T13:51:21.098+0000] {standard_task_runner.py:91} INFO - Job 234: Subtask load_data_to_warehouse
[2024-09-07T13:51:21.385+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-25T00:00:00+00:00 [running]> on host 3c1025a7eaca
[2024-09-07T13:51:21.887+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reddithackathon' AIRFLOW_CTX_DAG_ID='reddit_etl' AIRFLOW_CTX_TASK_ID='load_data_to_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-25T00:00:00+00:00'
[2024-09-07T13:51:21.889+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T13:51:22.149+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.203+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.249+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.305+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.393+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.459+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.525+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.592+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.638+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.709+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.759+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.797+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.858+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.915+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:22.963+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.004+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.072+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.128+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.194+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.235+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.273+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.314+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.377+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.444+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.506+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.559+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.622+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.692+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.740+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.796+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.851+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.912+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:23.962+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.025+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.057+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.099+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.155+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.217+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.269+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.316+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.394+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.461+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.526+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.595+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.682+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.726+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.776+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.834+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.879+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:24.960+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.042+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.119+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.174+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.211+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.252+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.301+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.348+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.387+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.451+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.501+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.553+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.606+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.663+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.705+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.745+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.795+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.835+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.894+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.943+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:25.990+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.038+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.079+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.121+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.203+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.243+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.290+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.339+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.378+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.426+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.455+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.493+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.546+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.582+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.642+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.695+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.751+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.785+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.873+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.937+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:26.999+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.088+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.154+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.205+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.302+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.397+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.556+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.634+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.680+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.787+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.844+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.883+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:27.953+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.022+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.071+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.113+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.189+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.259+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.297+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.351+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.400+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.456+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.498+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.554+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.663+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.728+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.789+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.834+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.871+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.906+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:28.955+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.027+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.071+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.148+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.189+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.244+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.331+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.386+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.458+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.514+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.567+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.606+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.665+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.731+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.798+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.851+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.893+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.945+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:29.993+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.034+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.097+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.146+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.200+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.270+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.341+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.405+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.466+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.514+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.564+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.610+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.689+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.750+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.827+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.874+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.939+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:30.984+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.044+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.092+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.149+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.197+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.244+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.293+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.360+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.459+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.529+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.586+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.643+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.697+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.790+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.865+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.908+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:31.963+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.019+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.049+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.098+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.173+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.218+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.269+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.331+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.369+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.411+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.466+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.503+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.549+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.622+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.655+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.713+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.776+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.844+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.917+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:32.992+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.031+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.079+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.129+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.210+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.272+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.346+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.402+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.467+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.524+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.580+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.632+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.685+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.730+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.793+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.859+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.935+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:33.984+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.033+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.081+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.120+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.175+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.251+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.332+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.405+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.473+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.530+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.612+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.670+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.721+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.776+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.858+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.916+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:34.955+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.026+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.056+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.101+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.162+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.201+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.254+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.302+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.335+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.376+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.437+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.488+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.534+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.568+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.602+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.635+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.682+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.727+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.766+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.807+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.844+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.880+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.933+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:35.983+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.034+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.080+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.159+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.208+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.247+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.284+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.323+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.377+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.420+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.477+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.511+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.562+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.602+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.640+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.684+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.720+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.755+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.795+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.833+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.872+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.909+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.944+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.973+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:36.997+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.029+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.075+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.106+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.145+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.183+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.217+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.252+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.287+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.323+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.363+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.402+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.437+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.468+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.502+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.544+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.586+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.625+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.669+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.702+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.738+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.775+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.844+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.897+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.927+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:37.967+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:38.012+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:38.050+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:38.089+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:38.140+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:38.197+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:38.202+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-07T13:51:38.207+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T13:51:38.264+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=reddit_etl, task_id=load_data_to_warehouse, execution_date=20240125T000000, start_date=20240907T135120, end_date=20240907T135138
[2024-09-07T13:51:38.324+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-07T13:51:38.391+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T13:51:38.395+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
