[2024-09-07T12:54:36.221+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T12:54:36.283+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-09-07T12:54:36.297+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-09-07T12:54:36.297+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-07T12:54:36.317+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_to_warehouse> on 2024-03-25 00:00:00+00:00
[2024-09-07T12:54:36.328+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1348) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-07T12:54:36.329+0000] {standard_task_runner.py:63} INFO - Started process 1351 to run task
[2024-09-07T12:54:36.328+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl', 'load_data_to_warehouse', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '382', '--raw', '--subdir', 'DAGS_FOLDER/reddit.py', '--cfg-path', '/tmp/tmpf757d076']
[2024-09-07T12:54:36.330+0000] {standard_task_runner.py:91} INFO - Job 382: Subtask load_data_to_warehouse
[2024-09-07T12:54:36.420+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-03-25T00:00:00+00:00 [running]> on host 42d604ea5ce6
[2024-09-07T12:54:36.564+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reddithackathon' AIRFLOW_CTX_DAG_ID='reddit_etl' AIRFLOW_CTX_TASK_ID='load_data_to_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-09-07T12:54:36.565+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T12:54:36.604+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.605+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.605+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.606+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.607+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.607+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.608+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.608+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.609+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.609+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.610+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.610+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.610+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.611+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.611+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.611+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.612+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.612+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.612+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.613+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.613+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.614+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.614+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.614+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.614+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.615+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.615+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.616+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.616+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.616+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.617+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.617+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.617+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.618+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.618+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.619+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.619+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.619+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.620+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.620+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.620+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.621+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.621+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.621+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.622+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.622+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.622+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.623+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.623+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.623+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.624+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.624+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.624+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.625+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.625+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.625+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.626+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.626+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.627+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.627+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.627+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.628+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.628+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.629+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.629+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.629+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.630+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.630+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.630+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.631+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.631+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.631+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.632+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.632+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.632+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.633+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.633+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.634+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.634+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.634+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.635+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.636+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.636+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.637+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.637+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.638+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.638+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.638+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.639+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.639+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.640+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.640+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.640+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.641+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.642+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.642+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.643+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.643+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.644+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.644+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.645+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.645+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.646+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.646+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.647+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.647+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.648+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.648+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.649+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.649+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.650+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.650+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.650+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.651+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.651+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.652+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.652+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.653+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.653+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.654+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.654+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.655+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.655+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.656+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.656+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.657+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.657+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.658+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.658+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.659+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.659+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.660+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.660+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.661+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.661+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.662+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.662+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.662+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.663+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.663+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.663+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.664+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.664+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.665+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.665+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.666+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.666+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.667+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.667+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.668+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.668+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.669+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.669+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.670+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.670+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.671+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.671+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.672+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.672+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.672+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.673+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.673+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.674+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.674+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.674+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.675+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.675+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.676+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.677+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.677+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.677+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.678+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.679+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.679+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.680+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.680+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.681+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.681+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.682+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.682+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.683+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.683+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.684+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.684+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.685+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.686+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.686+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.687+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.687+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.687+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.688+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.688+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.689+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.689+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.689+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.690+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.690+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.690+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.691+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.691+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.691+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.692+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.692+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.693+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.693+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.693+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.694+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.694+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.695+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.695+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.695+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.696+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.696+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.696+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.697+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.697+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.698+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.698+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.698+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.699+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.699+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.700+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.700+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.700+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.701+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.701+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.702+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.702+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.702+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.703+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.703+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.704+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.704+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.705+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.705+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.706+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.706+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.706+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.707+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.707+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.707+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.708+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.708+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.708+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.709+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.709+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.710+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.710+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.710+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.711+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.711+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.712+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.712+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.712+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.713+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.713+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.713+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.714+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.714+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.715+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.715+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.716+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.716+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.717+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.717+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.718+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.718+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.719+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.719+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.719+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.720+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.720+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.721+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.721+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.722+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.722+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.722+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.723+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.723+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.723+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.724+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.724+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.725+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.725+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.726+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.726+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.727+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.727+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.728+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.728+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.729+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.729+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.729+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.730+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.730+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.731+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.731+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.732+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.732+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.733+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:36.733+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-07T12:54:36.733+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T12:54:36.753+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=reddit_etl, task_id=load_data_to_warehouse, execution_date=20240325T000000, start_date=20240907T125436, end_date=20240907T125436
[2024-09-07T12:54:36.784+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-07T12:54:36.809+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T12:54:36.811+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-07T13:52:22.272+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T13:52:22.410+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-09-07T13:52:22.458+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-09-07T13:52:22.459+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-07T13:52:22.537+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_to_warehouse> on 2024-03-25 00:00:00+00:00
[2024-09-07T13:52:22.572+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=945) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-07T13:52:22.579+0000] {standard_task_runner.py:63} INFO - Started process 952 to run task
[2024-09-07T13:52:22.574+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl', 'load_data_to_warehouse', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/reddit.py', '--cfg-path', '/tmp/tmpcw0ryfcn']
[2024-09-07T13:52:22.582+0000] {standard_task_runner.py:91} INFO - Job 329: Subtask load_data_to_warehouse
[2024-09-07T13:52:22.987+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-03-25T00:00:00+00:00 [running]> on host 3c1025a7eaca
[2024-09-07T13:52:23.806+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reddithackathon' AIRFLOW_CTX_DAG_ID='reddit_etl' AIRFLOW_CTX_TASK_ID='load_data_to_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-09-07T13:52:23.808+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T13:52:24.021+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.170+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.232+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.301+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.379+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.466+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.531+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.591+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.655+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.723+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.777+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.883+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:24.959+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.008+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.072+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.154+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.218+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.276+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.314+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.383+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.437+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.479+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.522+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.581+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.625+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.679+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.740+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.810+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.896+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.926+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:25.976+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.030+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.067+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.131+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.187+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.257+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.299+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.364+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.401+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.472+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.552+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.612+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.648+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.703+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.772+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.843+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.928+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:26.982+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.021+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.130+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.221+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.295+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.353+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.398+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.455+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.506+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.578+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.659+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.724+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.790+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.849+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.905+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:27.987+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.072+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.111+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.152+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.246+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.324+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.392+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.457+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.520+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.583+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.644+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.681+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.718+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.788+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.883+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:28.984+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.056+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.099+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.177+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.249+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.299+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.373+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.438+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.484+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.548+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.633+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.682+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.744+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.806+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.843+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.895+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:29.937+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.011+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.064+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.129+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.178+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.215+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.276+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.350+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.399+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.450+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.514+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.570+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.612+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.680+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.728+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.776+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.813+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.889+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:30.955+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.031+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.096+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.165+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.238+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.292+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.375+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.432+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.489+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.527+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.573+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.615+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.681+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.735+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.796+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.855+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.910+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:31.952+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.005+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.046+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.083+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.146+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.186+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.257+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.321+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.379+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.436+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.494+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.542+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.607+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.656+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.716+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.771+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.845+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.908+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:32.958+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.009+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.080+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.137+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.187+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.235+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.303+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.353+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.400+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.468+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.545+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.630+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.689+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.744+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.814+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.865+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.931+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:33.966+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.022+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.080+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.123+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.165+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.205+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.270+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.314+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.364+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.414+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.455+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.494+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.541+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.576+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.622+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.657+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.711+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.758+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.801+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.844+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.889+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.938+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:34.971+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.010+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.064+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.110+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.162+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.234+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.309+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.367+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.411+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.459+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.505+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.547+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.582+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.626+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.687+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.759+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.828+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.876+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.923+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:35.981+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.047+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.135+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.200+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.237+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.270+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.308+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.345+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.383+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.419+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.467+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.543+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.638+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.705+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.739+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.787+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.828+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.881+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:36.935+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.020+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.066+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.108+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.167+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.232+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.280+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.331+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.379+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.430+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.474+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.535+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.591+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.651+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.697+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.748+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.812+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.882+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.929+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:37.981+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.035+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.081+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.159+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.205+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.258+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.301+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.347+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.426+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.485+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.520+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.578+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.636+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.684+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.726+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.773+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.812+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.862+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.910+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.960+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:38.998+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.053+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.097+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.134+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.169+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.212+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.249+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.280+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.314+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.370+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.405+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.464+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.499+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.542+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.577+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.618+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.650+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.696+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.739+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.771+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.803+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.847+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.893+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.927+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:39.972+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.019+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.059+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.102+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.156+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.206+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.240+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.273+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.307+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.354+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.387+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.422+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.453+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.482+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.512+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:52:40.514+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-07T13:52:40.516+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T13:52:40.586+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=reddit_etl, task_id=load_data_to_warehouse, execution_date=20240325T000000, start_date=20240907T135222, end_date=20240907T135240
[2024-09-07T13:52:40.630+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-07T13:52:40.692+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T13:52:40.694+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
