[2024-09-07T12:54:11.313+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T12:54:11.411+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-07T12:54:11.427+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-07T12:54:11.427+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-07T12:54:11.572+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_to_warehouse> on 2024-01-03 00:00:00+00:00
[2024-09-07T12:54:11.601+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1107) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-07T12:54:11.603+0000] {standard_task_runner.py:63} INFO - Started process 1119 to run task
[2024-09-07T12:54:11.608+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl', 'load_data_to_warehouse', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/reddit.py', '--cfg-path', '/tmp/tmpbi1sy48g']
[2024-09-07T12:54:11.618+0000] {standard_task_runner.py:91} INFO - Job 271: Subtask load_data_to_warehouse
[2024-09-07T12:54:11.832+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-03T00:00:00+00:00 [running]> on host 42d604ea5ce6
[2024-09-07T12:54:12.125+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reddithackathon' AIRFLOW_CTX_DAG_ID='reddit_etl' AIRFLOW_CTX_TASK_ID='load_data_to_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2024-09-07T12:54:12.130+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T12:54:12.220+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.224+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.225+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.225+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.226+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.227+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.228+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.228+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.229+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.229+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.230+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.230+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.231+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.231+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.232+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.233+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.233+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.234+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.234+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.235+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.236+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.236+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.237+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.237+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.238+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.238+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.239+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.239+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.240+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.241+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.241+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.242+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.242+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.243+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.243+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.244+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.244+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.245+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.245+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.246+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.247+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.247+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.248+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.248+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.249+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.249+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.250+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.250+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.251+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.251+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.252+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.252+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.253+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.253+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.254+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.255+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.255+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.256+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.256+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.257+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.257+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.258+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.258+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.258+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.259+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.261+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.262+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.263+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.267+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.268+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.268+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.269+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.269+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.270+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.270+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.271+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.271+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.275+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.275+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.276+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.276+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.277+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.277+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.278+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.278+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.284+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.285+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.285+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.286+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.286+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.287+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.287+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.294+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.295+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.295+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.296+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.296+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.297+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.297+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.301+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.302+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.302+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.303+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.303+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.308+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.308+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.309+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.309+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.310+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.310+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.315+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.316+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.316+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.317+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.317+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.318+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.318+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.319+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.321+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.322+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.322+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.323+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.323+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.324+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.325+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.325+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.325+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.326+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.326+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.327+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.327+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.332+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.333+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.333+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.334+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.334+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.340+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.341+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.341+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.342+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.342+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.343+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.343+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.344+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.344+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.349+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.352+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.353+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.353+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.354+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.354+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.357+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.358+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.358+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.360+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.360+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.361+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.361+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.362+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.362+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.364+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.364+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.365+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.366+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.366+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.367+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.367+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.368+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.369+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.369+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.370+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.370+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.371+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.372+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.372+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.373+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.373+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.374+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.375+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.375+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.376+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.376+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.376+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.377+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.377+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.378+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.385+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.386+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.386+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.387+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.387+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.392+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.393+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.393+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.394+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.394+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.395+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.396+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.396+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.397+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.397+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.398+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.398+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.402+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.403+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.403+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.404+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.405+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.405+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.406+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.406+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.407+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.407+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.408+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.408+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.409+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.409+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.410+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.410+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.411+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.412+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.412+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.413+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.413+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.414+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.414+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.415+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.415+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.416+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.416+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.417+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.417+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.418+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.418+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.419+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.419+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.420+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.421+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.421+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.422+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.422+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.423+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.423+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.424+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.424+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.425+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.425+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.426+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.426+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.427+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.427+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.428+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.428+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.429+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.430+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.430+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.431+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.431+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.432+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.432+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.433+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.434+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.434+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.435+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.435+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.436+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.436+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.437+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.437+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.438+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.438+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.439+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.440+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.440+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.441+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.441+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.442+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.442+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.443+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.443+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.443+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.444+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.444+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.445+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.445+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.446+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.446+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.447+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.447+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.448+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.448+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.449+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.449+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.449+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.450+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.451+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.451+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.452+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.452+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.453+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:12.454+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-07T12:54:12.454+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T12:54:12.489+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=reddit_etl, task_id=load_data_to_warehouse, execution_date=20240103T000000, start_date=20240907T125411, end_date=20240907T125412
[2024-09-07T12:54:12.599+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-07T12:54:12.700+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T12:54:12.710+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-07T13:50:52.972+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T13:50:53.153+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-07T13:50:53.191+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-07T13:50:53.192+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-07T13:50:53.309+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_to_warehouse> on 2024-01-03 00:00:00+00:00
[2024-09-07T13:50:53.347+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=644) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-07T13:50:53.349+0000] {standard_task_runner.py:63} INFO - Started process 648 to run task
[2024-09-07T13:50:53.344+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl', 'load_data_to_warehouse', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/reddit.py', '--cfg-path', '/tmp/tmp8ztcytgh']
[2024-09-07T13:50:53.353+0000] {standard_task_runner.py:91} INFO - Job 193: Subtask load_data_to_warehouse
[2024-09-07T13:50:53.701+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2024-01-03T00:00:00+00:00 [running]> on host 3c1025a7eaca
[2024-09-07T13:50:54.259+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reddithackathon' AIRFLOW_CTX_DAG_ID='reddit_etl' AIRFLOW_CTX_TASK_ID='load_data_to_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2024-09-07T13:50:54.261+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T13:50:54.450+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.502+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.558+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.605+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.646+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.692+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.738+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.790+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.855+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.924+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.981+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.050+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.113+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.157+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.220+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.280+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.323+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.372+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.426+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.515+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.583+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.645+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.684+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.757+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.821+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.911+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.961+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.996+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.071+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.111+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.183+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.231+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.285+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.331+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.378+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.454+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.525+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.615+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.673+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.728+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.840+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.904+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.983+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.104+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.193+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.249+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.303+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.369+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.437+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.525+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.575+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.617+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.700+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.756+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.828+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.909+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.971+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.056+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.119+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.194+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.274+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.319+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.446+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.504+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.556+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.648+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.696+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.803+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.851+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.933+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.992+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.047+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.120+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.166+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.216+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.275+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.373+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.441+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.529+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.597+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.659+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.713+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.781+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.885+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.998+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.054+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.098+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.163+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.240+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.342+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.407+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.485+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.556+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.655+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.726+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.800+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.850+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.886+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.988+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.034+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.089+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.154+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.213+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.265+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.317+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.389+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.440+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.518+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.567+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.623+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.678+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.762+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.834+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.897+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.949+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.006+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.067+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.170+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.215+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.271+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.327+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.395+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.456+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.520+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.587+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.678+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.764+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.919+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.980+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.025+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.067+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.121+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.198+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.256+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.315+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.348+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.424+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.497+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.565+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.636+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.685+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.738+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.793+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.841+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.913+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.976+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.021+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.096+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.168+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.246+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.319+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.352+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.402+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.451+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.492+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.553+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.628+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.700+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.796+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.874+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.927+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.993+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.051+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.112+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.187+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.264+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.333+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.423+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.475+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.562+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.646+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.742+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.799+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.844+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.943+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.010+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.053+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.105+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.159+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.221+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.267+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.301+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.345+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.394+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.433+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.487+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.529+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.581+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.637+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.684+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.715+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.758+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.786+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.824+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.868+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.901+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.939+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:06.984+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.033+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.082+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.119+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.156+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.189+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.232+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.273+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.315+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.364+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.406+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.444+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.488+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.518+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.556+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.594+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.628+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.670+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.699+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.738+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.768+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.801+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.829+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.866+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.898+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.929+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.961+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:07.993+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.026+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.058+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.088+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.124+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.164+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.205+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.232+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.262+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.301+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.333+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.359+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.400+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.430+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.462+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.492+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.523+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.596+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.632+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.658+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.685+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.708+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.731+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.756+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.777+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.798+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.824+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.851+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.874+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.896+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.919+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.947+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.965+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:08.987+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.010+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.031+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.053+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.077+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.100+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.122+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.140+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.159+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.175+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.198+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.218+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.237+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.261+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.283+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.305+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.325+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.346+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.366+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.383+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.408+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.424+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.447+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.470+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.490+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.507+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.523+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.544+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.563+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.580+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.602+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.624+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.645+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.667+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.684+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.700+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.719+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.734+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.750+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.772+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.793+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.815+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.837+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:09.839+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-07T13:51:09.839+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T13:51:09.874+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=reddit_etl, task_id=load_data_to_warehouse, execution_date=20240103T000000, start_date=20240907T135053, end_date=20240907T135109
[2024-09-07T13:51:09.909+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-07T13:51:09.941+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T13:51:09.942+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
