[2024-09-07T12:54:03.252+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T12:54:03.350+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2024-09-07T12:54:03.380+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2024-09-07T12:54:03.381+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-07T12:54:03.446+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_to_warehouse> on 2023-12-12 00:00:00+00:00
[2024-09-07T12:54:03.473+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1032) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-07T12:54:03.476+0000] {standard_task_runner.py:63} INFO - Started process 1042 to run task
[2024-09-07T12:54:03.471+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl', 'load_data_to_warehouse', 'scheduled__2023-12-12T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/reddit.py', '--cfg-path', '/tmp/tmp42f_llps']
[2024-09-07T12:54:03.479+0000] {standard_task_runner.py:91} INFO - Job 231: Subtask load_data_to_warehouse
[2024-09-07T12:54:03.699+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-12T00:00:00+00:00 [running]> on host 42d604ea5ce6
[2024-09-07T12:54:04.040+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reddithackathon' AIRFLOW_CTX_DAG_ID='reddit_etl' AIRFLOW_CTX_TASK_ID='load_data_to_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2023-12-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-12T00:00:00+00:00'
[2024-09-07T12:54:04.041+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T12:54:04.120+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.120+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.121+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.121+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.122+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.122+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.127+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.128+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.128+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.129+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.129+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.130+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.130+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.131+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.131+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.132+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.133+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.133+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.134+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.134+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.135+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.135+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.136+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.137+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.138+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.139+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.141+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.141+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.142+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.144+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.144+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.145+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.145+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.146+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.147+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.147+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.148+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.148+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.149+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.149+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.150+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.151+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.152+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.153+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.154+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.154+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.155+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.155+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.156+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.156+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.157+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.158+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.158+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.159+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.159+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.160+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.160+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.163+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.163+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.164+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.164+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.167+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.168+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.169+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.170+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.173+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.173+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.174+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.174+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.175+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.175+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.176+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.176+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.177+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.177+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.178+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.178+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.179+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.179+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.180+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.180+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.181+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.181+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.182+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.182+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.183+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.184+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.184+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.185+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.188+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.190+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.191+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.191+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.193+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.194+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.195+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.195+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.196+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.196+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.197+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.197+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.198+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.198+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.199+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.199+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.200+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.201+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.201+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.202+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.203+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.203+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.204+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.204+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.205+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.205+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.206+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.206+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.207+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.207+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.208+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.208+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.209+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.209+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.210+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.210+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.211+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.211+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.212+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.212+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.213+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.213+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.214+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.214+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.215+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.215+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.216+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.216+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.217+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.217+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.219+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.220+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.221+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.221+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.222+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.222+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.223+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.223+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.224+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.224+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.225+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.225+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.226+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.226+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.227+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.227+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.228+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.228+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.229+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.230+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.231+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.233+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.234+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.236+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.237+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.238+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.238+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.239+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.239+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.239+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.240+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.240+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.241+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.241+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.242+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.242+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.243+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.243+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.244+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.244+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.245+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.245+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.246+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.246+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.250+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.253+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.253+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.255+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.255+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.256+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.257+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.257+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.258+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.258+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.259+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.260+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.260+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.261+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.261+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.262+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.263+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.263+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.266+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.267+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.268+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.269+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.270+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.270+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.271+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.271+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.272+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.273+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.273+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.274+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.274+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.275+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.275+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.276+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.276+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.277+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.277+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.278+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.278+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.279+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.279+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.280+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.280+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.281+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.281+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.282+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.282+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.283+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.284+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.284+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.285+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.286+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.286+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.287+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.288+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.288+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.289+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.289+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.290+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.290+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.291+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.292+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.292+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.293+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.294+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.294+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.295+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.296+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.296+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.297+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.298+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.298+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.299+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.300+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.300+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.301+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.302+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.302+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.303+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.304+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.304+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.305+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.305+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.306+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.306+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.307+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.307+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.308+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.309+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.309+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.310+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.310+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.311+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.311+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.312+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.312+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.313+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.313+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.314+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.314+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.315+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.316+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.317+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.317+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.318+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.319+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.320+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.320+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.321+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.322+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.322+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.323+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.323+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.324+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.324+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.325+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.325+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.326+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-07T12:54:04.327+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T12:54:04.364+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=reddit_etl, task_id=load_data_to_warehouse, execution_date=20231212T000000, start_date=20240907T125403, end_date=20240907T125404
[2024-09-07T12:54:04.560+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-07T12:54:04.646+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T12:54:04.661+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-07T13:50:45.186+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T13:50:45.366+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2024-09-07T13:50:45.425+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2024-09-07T13:50:45.431+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-07T13:50:45.539+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_to_warehouse> on 2023-12-12 00:00:00+00:00
[2024-09-07T13:50:45.596+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=610) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-07T13:50:45.607+0000] {standard_task_runner.py:63} INFO - Started process 621 to run task
[2024-09-07T13:50:45.594+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl', 'load_data_to_warehouse', 'scheduled__2023-12-12T00:00:00+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/reddit.py', '--cfg-path', '/tmp/tmp3by44wm4']
[2024-09-07T13:50:45.614+0000] {standard_task_runner.py:91} INFO - Job 178: Subtask load_data_to_warehouse
[2024-09-07T13:50:45.946+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-12T00:00:00+00:00 [running]> on host 3c1025a7eaca
[2024-09-07T13:50:46.597+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reddithackathon' AIRFLOW_CTX_DAG_ID='reddit_etl' AIRFLOW_CTX_TASK_ID='load_data_to_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2023-12-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-12T00:00:00+00:00'
[2024-09-07T13:50:46.599+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T13:50:46.876+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:46.923+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:46.957+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:46.994+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.051+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.094+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.162+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.249+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.341+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.395+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.431+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.462+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.503+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.535+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.572+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.604+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.644+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.696+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.783+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.868+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.916+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.949+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.998+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.094+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.173+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.235+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.327+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.421+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.471+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.518+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.554+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.593+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.639+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.681+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.738+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.788+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.841+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.893+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.942+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.033+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.096+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.167+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.210+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.268+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.308+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.365+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.426+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.481+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.529+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.559+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.587+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.621+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.663+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.708+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.775+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.835+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.907+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.988+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.047+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.129+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.171+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.231+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.295+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.354+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.435+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.479+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.568+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.642+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.729+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.820+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.877+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.908+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.992+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.085+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.133+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.169+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.225+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.297+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.394+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.504+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.574+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.628+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.704+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.759+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.797+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.831+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.871+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.952+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.985+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.018+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.058+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.114+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.160+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.223+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.273+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.327+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.381+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.427+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.496+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.549+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.602+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.650+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.693+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.739+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.796+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.845+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.885+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.925+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.968+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.025+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.071+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.119+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.165+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.235+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.299+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.370+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.430+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.497+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.580+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.667+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.747+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.798+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.835+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.883+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.931+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.983+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.036+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.098+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.163+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.212+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.254+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.308+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.366+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.426+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.474+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.523+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.557+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.598+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.646+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.712+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.766+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.808+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.891+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.971+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.037+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.088+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.140+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.187+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.221+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.264+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.311+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.354+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.400+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.487+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.554+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.695+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.759+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.824+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.895+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.953+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.015+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.078+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.151+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.218+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.296+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.334+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.377+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.423+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.478+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.575+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.623+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.702+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.751+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.793+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.847+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.893+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.938+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.048+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.103+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.164+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.278+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.344+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.440+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.535+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.602+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.709+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.781+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.838+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.890+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.930+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.025+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.095+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.158+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.213+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.256+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.306+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.396+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.474+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.591+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.686+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.764+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.822+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.880+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.962+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.071+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.157+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.223+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.297+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.397+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.481+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.564+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.626+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.682+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.754+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.838+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.946+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.073+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.177+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.283+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.380+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.415+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.495+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.556+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.644+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.722+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.778+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.858+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.921+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.989+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.078+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.148+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.226+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.271+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.313+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.381+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.430+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.497+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.562+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.601+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.641+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.678+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.729+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.799+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.851+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.917+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.973+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.037+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.081+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.127+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.181+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.237+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.291+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.360+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.440+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.500+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.569+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.686+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.730+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.797+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.978+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.089+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.139+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.209+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.266+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.336+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.402+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.469+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.534+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.608+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.681+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.731+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.799+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.871+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.930+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.973+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.019+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.090+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.159+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.260+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.319+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.392+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.465+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.543+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.614+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.664+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.738+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.792+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.877+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.964+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.037+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.111+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.164+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.250+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.324+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.380+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.475+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.562+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.689+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.795+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.883+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:05.886+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-07T13:51:05.887+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T13:51:05.969+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=reddit_etl, task_id=load_data_to_warehouse, execution_date=20231212T000000, start_date=20240907T135045, end_date=20240907T135105
[2024-09-07T13:51:06.198+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-07T13:51:06.301+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T13:51:06.311+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
