[2024-09-07T12:54:03.182+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T12:54:03.311+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2024-09-07T12:54:03.338+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2024-09-07T12:54:03.339+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-07T12:54:03.373+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_to_warehouse> on 2023-12-14 00:00:00+00:00
[2024-09-07T12:54:03.397+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1030) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-07T12:54:03.398+0000] {standard_task_runner.py:63} INFO - Started process 1037 to run task
[2024-09-07T12:54:03.394+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl', 'load_data_to_warehouse', 'scheduled__2023-12-14T00:00:00+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/reddit.py', '--cfg-path', '/tmp/tmp7f3cc0l_']
[2024-09-07T12:54:03.401+0000] {standard_task_runner.py:91} INFO - Job 230: Subtask load_data_to_warehouse
[2024-09-07T12:54:03.600+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-14T00:00:00+00:00 [running]> on host 42d604ea5ce6
[2024-09-07T12:54:03.844+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reddithackathon' AIRFLOW_CTX_DAG_ID='reddit_etl' AIRFLOW_CTX_TASK_ID='load_data_to_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-14T00:00:00+00:00'
[2024-09-07T12:54:03.845+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T12:54:03.943+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.947+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.950+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.951+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.951+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.952+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.952+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.953+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.953+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.956+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.958+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.959+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.960+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.961+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.963+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.965+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.967+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.968+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.970+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.972+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.973+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.974+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.976+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.977+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.978+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.980+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.982+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.984+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.985+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.987+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.988+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.989+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.990+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.992+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.994+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.994+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.995+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:03.999+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.001+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.002+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.007+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.007+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.008+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.009+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.010+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.011+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.017+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.019+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.020+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.021+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.022+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.023+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.025+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.025+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.026+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.027+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.027+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.028+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.028+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.029+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.029+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.030+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.031+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.031+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.032+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.034+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.035+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.036+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.037+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.037+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.038+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.039+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.039+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.040+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.040+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.041+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.042+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.042+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.043+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.043+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.044+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.044+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.045+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.047+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.049+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.050+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.051+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.051+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.052+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.053+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.053+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.054+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.054+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.055+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.055+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.056+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.056+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.057+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.058+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.059+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.059+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.060+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.061+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.061+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.062+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.063+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.064+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.065+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.066+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.067+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.068+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.068+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.069+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.069+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.070+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.071+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.071+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.072+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.072+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.072+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.073+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.074+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.074+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.075+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.075+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.076+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.076+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.077+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.077+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.078+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.078+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.079+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.080+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.080+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.081+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.081+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.082+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.083+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.083+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.084+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.084+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.085+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.086+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.086+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.087+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.087+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.088+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.088+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.089+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.090+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.090+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.091+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.091+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.092+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.092+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.093+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.093+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.094+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.094+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.095+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.095+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.096+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.096+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.096+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.097+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.097+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.097+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.098+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.098+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.098+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.099+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.099+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.099+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.100+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.100+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.100+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.101+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.101+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.102+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.103+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.103+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.104+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.105+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.105+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.106+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.106+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.107+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.107+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.108+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.108+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.109+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.109+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.110+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.110+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.111+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.111+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.112+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.112+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.113+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.113+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.114+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.114+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.115+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.115+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.116+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.117+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.117+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.118+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.119+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.119+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.120+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.120+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.121+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.121+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.122+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.122+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.123+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.123+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.124+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.124+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.125+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.125+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.126+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.126+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.127+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.127+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.128+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.128+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.129+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.129+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.130+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.131+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.131+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.132+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.132+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.133+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.133+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.134+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.134+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.135+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.135+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.136+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.137+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.138+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.139+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.139+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.140+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.140+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.141+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.141+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.142+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.142+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.143+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.144+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.144+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.145+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.145+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.146+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.146+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.147+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.147+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.148+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.148+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.149+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.149+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.150+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.151+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.152+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.152+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.153+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.154+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.154+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.154+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.155+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.156+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.156+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.157+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.157+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.158+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.158+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.159+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.159+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.160+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.160+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.161+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.161+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.162+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.162+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.163+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.163+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.164+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.164+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.165+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.166+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.166+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.167+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.167+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.168+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.169+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.170+0000] {logging_mixin.py:188} INFO - Error loading data: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-09-07T12:54:04.170+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-07T12:54:04.171+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T12:54:04.222+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=reddit_etl, task_id=load_data_to_warehouse, execution_date=20231214T000000, start_date=20240907T125403, end_date=20240907T125404
[2024-09-07T12:54:04.318+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-07T12:54:04.565+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T12:54:04.570+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-07T13:50:45.021+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T13:50:45.235+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2024-09-07T13:50:45.272+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2024-09-07T13:50:45.274+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-07T13:50:45.424+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_to_warehouse> on 2023-12-14 00:00:00+00:00
[2024-09-07T13:50:45.464+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=608) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-07T13:50:45.469+0000] {standard_task_runner.py:63} INFO - Started process 616 to run task
[2024-09-07T13:50:45.468+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl', 'load_data_to_warehouse', 'scheduled__2023-12-14T00:00:00+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/reddit.py', '--cfg-path', '/tmp/tmpiptws4vq']
[2024-09-07T13:50:45.473+0000] {standard_task_runner.py:91} INFO - Job 176: Subtask load_data_to_warehouse
[2024-09-07T13:50:45.824+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl.load_data_to_warehouse scheduled__2023-12-14T00:00:00+00:00 [running]> on host 3c1025a7eaca
[2024-09-07T13:50:46.590+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reddithackathon' AIRFLOW_CTX_DAG_ID='reddit_etl' AIRFLOW_CTX_TASK_ID='load_data_to_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-14T00:00:00+00:00'
[2024-09-07T13:50:46.594+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T13:50:46.838+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:46.901+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:46.967+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.018+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.072+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.129+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.179+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.225+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.279+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.334+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.376+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.411+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.452+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.512+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.549+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.607+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.646+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.735+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.777+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.873+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.919+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.951+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:47.994+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.032+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.065+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.154+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.245+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.316+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.382+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.456+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.525+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.578+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.627+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.690+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.754+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.819+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.878+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:48.955+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.036+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.138+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.243+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.282+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.326+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.375+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.418+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.452+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.504+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.542+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.579+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.610+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.638+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.680+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.743+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.829+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.887+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.933+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:49.969+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.036+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.080+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.157+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.256+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.295+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.329+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.364+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.410+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.489+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.525+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.564+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.602+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.640+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.696+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.742+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.851+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:50.896+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.056+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.176+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.253+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.302+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.384+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.466+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.533+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.572+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.603+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.638+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.698+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.774+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.821+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.870+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:51.944+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.006+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.046+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.079+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.137+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.173+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.207+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.244+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.329+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.377+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.413+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.471+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.535+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.569+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.603+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.667+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.718+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.764+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.816+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.874+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.950+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:52.992+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.022+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.093+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.136+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.188+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.228+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.277+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.335+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.397+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.457+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.502+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.561+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.634+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.680+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.723+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.769+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.817+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.865+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.906+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:53.955+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.000+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.052+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.102+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.143+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.212+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.257+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.309+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.360+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.418+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.455+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.501+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.561+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.612+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.660+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.705+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.755+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.795+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.852+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.904+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:54.945+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.003+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.075+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.159+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.209+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.249+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.300+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.339+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.382+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.435+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.471+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.546+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.596+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.648+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.707+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.770+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.850+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.908+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:55.965+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.010+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.061+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.133+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.199+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.234+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.279+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.340+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.399+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.473+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.542+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.632+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.739+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.823+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.899+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:56.974+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.022+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.064+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.112+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.179+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.253+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.325+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.396+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.459+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.543+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.600+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.683+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.725+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.789+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.837+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.882+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.934+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:57.990+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.046+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.122+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.202+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.284+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.370+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.454+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.554+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.599+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.662+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.709+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.753+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.824+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:58.935+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.048+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.104+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.178+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.240+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.319+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.368+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.439+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.500+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.569+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.612+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.661+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.726+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.808+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.901+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:50:59.963+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.049+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.135+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.287+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.380+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.464+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.546+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.648+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.741+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.826+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.899+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:00.952+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.016+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.061+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.111+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.192+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.251+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.307+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.344+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.422+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.518+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.579+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.647+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.718+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.781+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.844+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.920+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:01.984+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.082+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.136+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.200+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.267+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.311+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.362+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.405+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.452+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.520+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.580+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.622+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.679+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.726+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.802+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.872+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:02.975+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.020+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.068+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.150+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.198+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.263+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.323+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.364+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.427+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.488+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.534+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.582+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.667+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.731+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.804+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.864+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.907+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.948+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:03.992+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.058+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.176+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.234+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.302+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.388+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.455+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.509+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.601+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.648+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.706+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.763+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.824+0000] {logging_mixin.py:188} INFO - Error loading data: relation "dim_author" does not exist
LINE 2:             INSERT INTO dim_author (author_id, author_name)
                                ^
[2024-09-07T13:51:04.834+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-07T13:51:04.837+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T13:51:04.951+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=reddit_etl, task_id=load_data_to_warehouse, execution_date=20231214T000000, start_date=20240907T135045, end_date=20240907T135104
[2024-09-07T13:51:05.224+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-07T13:51:05.400+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T13:51:05.407+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
